config/routes.rb
Rails.application.routes.draw do
 
  root 'publics#index'

resource :tests, :except => [:show]

  
  # pubic controller route
  get 'show/:permalink', to: 'publics#show'

  # user controller routes
  get '/login', to: 'users#login'
  post '/login_attempt', to: 'users#login_attempt'
  get 'admin/logout', to: 'users#logout'
  get 'admin/index', to: 'users#index'

  # AdminUser Controller routes
  get 'admin/users/index', to: 'admin_users#index', as: 'index_admin'
  get 'admin/users/new', to: 'admin_users#new', as: 'new_admin'
  post 'admin/users/create', to: 'admin_users#create', as: 'create_admin'
  get 'admin/users/:id/edit', to: 'admin_users#edit', as: 'edit_admin'
  post 'admin/users/:id', to: 'admin_users#update', as: 'update_admin'
  get 'admin/users/:id', to: 'admin_users#destroy', as: 'destroy_admin'

  # Subject Controller routes
  get 'admin/subjects/index/', to: 'subjects#index', as: 'index_subject'
  get 'admin/subjects/show', to: 'subjects#show', as: 'show_subject'
  get 'admin/subjects/new', to: 'subjects#new', as: 'new_subject'
  post 'admin/subjects/create', to: 'subjects#create', as: 'create_subject'
  get 'admin/subjects/:id/edit', to: 'subjects#edit', as: 'edit_subject'
  post 'admin/subjects/users/:id', to: 'subjects#update', as: 'update_subject'
  get 'admin/subjects/:id/delete', to: 'subjects#delete'
  post 'admin/subjects/:id', to: 'subjects#destroy'

  # Pages Controller route
  get 'admin/subjects/pages/index', to: 'pages#index'
  get 'admin/subjects/pages/new', to: 'pages#new'
  get 'admin/subjects/pages/:id', to: 'pages#show'
  post 'admin/subjects/pages/create', to: 'pages#create'
  get 'admin/subjects/pages/:id/edit', to: 'pages#edit'
  post 'admin/subjects/pages/:id', to: 'pages#update'
  get 'admin/subjects/pages/:id/delete', to: 'pages#delete'
  delete 'admin/subjects/pages/:id', to: 'pages#destroy'


  # Section Controller route
  get 'admin/subjects/pages/sections/index', to: 'sections#index'
  get 'admin/subjects/pages/sections/new', to: 'sections#new'
  get 'admin/subjects/pages/sections/:id', to: 'sections#show'
  post 'admin/subjects/pages/sections/create', to: 'sections#create'
  get 'admin/subjects/pages/sections/:id/edit', to: 'sections#edit'
  post 'admin/subjects/pages/sections/:id', to: 'sections#update'
  get 'admin/subjects/pages/sections/:id/delete', to: 'sections#delete'
  delete 'admin/subjects/pages/sections/:id', to: 'sections#destroy'

  match ':controller(/:action(/:id))', :via => [:get, :post]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :pages, :dependent =>  :destroy
    has_one_attached :image

    acts_as_list

    validates :name, :presence => true,
                     :length => { :minimum => 2 },
                     :uniqueness => true
    validates_presence_of :position

    # image validation
    validates :image, :presence => true, format: { with: %r{.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }, on: :create

    # namescope(shortcut) queries of where, order and search
    scope :visible, lambda{where(:visible => true)}
    scope :invisible, lambda{where(:visible => false)}
    scope :search, lambda{ |query| where(['name LIKE ?', '%' + query +'%'])}
    scope :sorted, lambda{order("subjects.position ASC")}
    scope :new_first, lambda{order('subjects.created_at DESC')}



    def image_as_thumbnails
        return unless image.content_type.in?(%w[image/jpeg, image/png])
        image.variant(resize_to_limit: [100, 100]).processed
    end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
      include ActiveStorage::SetCurrent

  def index
    if params[:search].present?
      @subjects = Subject.where('name LIKE ?', "%#{params[:search]}%")
    else
    @subjects = Subject.sorted
    end
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
    @subject_count = Subject.count + 1
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:success] = 'Subject added successfully'
      redirect_to(:action => 'index')
    else
      @subject_count = Subject.count + 1
      render 'new'
    end
  end

  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      flash[:success] = 'Subject Updated Successfully'
      redirect_to(:action => 'index', :id => @subject.id)
    else
      @subject_count = Subject.count
      render 'edit'
    end
  end

 def delete
  @subject = Subject.find(params[:id])
 end

  def destroy
    subject = Subject.find(params[:id]).destroy
    flash[:success] = 'Subject ' + subject.name + ' Deleted Successfully'
    redirect_to(:action => 'index')
  end

  private
  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :image)
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<div class="input-form">
    <%= f.label(:name) %>
        <p>
            <%= f.text_field(:name, class:'form-control') %>
                <% if @subject.errors.any? %>
                    <span class='error'>
                        <ul>
                            <% @subject.errors.full_messages_for(:name).each do |message| %>
                                <li class="text-danger">
                                    <%= message %>
                                </li>
                                <% end %>
                        </ul>
                    </span>
                    <% end %>
        </p>
</div>
<div>
    <%= f.label(:position) %>
        <p>
            <%= f.select(:position, 1..@subject_count, {:prompt=>true}, {class:'form-select'}) %>
                <% if @subject.errors.any? %>
                    <span class='error'>
                        <ul>
                            <% @subject.errors.full_messages_for(:position).each do |message| %>
                                <li class="text-danger">
                                    <%= message %>
                                </li>
                                <% end %>
                        </ul>
                    </span>
                    <% end %>
        </p>
</div>
<div>
    <%= f.label(:visible) %>
        <p>
            <%= f.check_box(:visible, class:'form-check-input') %>
        </p>
</div>
<div>
    <%= f.label(:image, "Image") %>
        <p>
            <%= f.file_field(:image, value: @subject.image.url, class:'form-file-input') %>
            <!-- <%= image_tag @subject.image_as_thumbnails if @subject.image.present? %> -->
            <% if @subject.errors.any? %>
                <span class='error'>
                    <ul>
                        <% @subject.errors.full_messages_for(:image).each do |message| %>
                            <li class="text-danger">
                                <%= message %>
                            </li>
                            <% end %>
                    </ul>
                </span>
                <% end %>
        </p>
</div>

app/views/subjects/delete.html.erb
<% @page_title='Subject' %>
    <div class="container">
        <%= link_to('Back', {:action=> 'index'}, class:'btn btn-light ') %>

            <div class="ms-5 mt-3 ps-3 bg-light col-5">

                <h1>Delete Form</h1>
            <%= form_tag({:action=> 'destroy', :id => @subject.id} ) do %>
                    <p>Are you sure you want to delete this <b><%= @subject.name %></b> Subject?</p>
                        
                    <div class="ms-5">
                        <%= submit_tag("Delete", class: 'btn btn-success mb-3' ) %>
                    </div>
            </div>
            <% end %>
    </div>

 

app/views/subjects/edit.html.erb
<% @page_title='Subject' %>
    <div class="container">
        <%= link_to('Back', {:action=> 'index'}, class:'btn btn-light ') %>

            <div class="ms-5 mt-3 ps-3 bg-light col-5">

                <h1>Update Form</h1>

                <%= form_for :subject, url:{:action=> 'update', :id => @subject.id, html: { multipart: true }}, method: :post do |f| %>

                    <%= render(:partial=> 'form', :locals => {:f => f}) %>
                        
                    <div class="ms-3">
                    <%= submit_tag('Update', class:'btn btn-primary mb-3 ') %>
                    </div>
                <% end %>
            </div>
    </div>

app/views/subjects/index.html.erb
<% @page_title='Subjects' %>

    <%= link_to('Add New Subject', new_subject_path, class:'btn btn-primary ') %>
        <div class="float-end">
             <%= link_to(' Admin Menu', {controller: 'users' , action: 'index' }, class:'btn btn-light') %>
        </div>

        <table class="table">
            <div class="container">
                <h5 class="mt-2">
                    <%= pluralize(@subjects.size, 'Total Subjects' ) %>
                </h5>
                <h1 class="d-flex justify-content-center">Subjects Table</h1>
            </div>
            <div class="float-end">
                <%= form_with model: @subject, :action=> index_subject_path, method: :get do |f| %>
                    <span>
                        <%= link_to('X', {:action=> "index"}, class:'text-decoration-none text-dark btn') %>
                    </span>
                    <%= f.text_field :search %>
                        <%= submit_tag 'Search' %>
                            <% end %>
            </div>
            <thead>
                <tr>
                    <th scope="col">Position</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Visible</th>
                    <th scope="col">Pages</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <% if @subjects.blank? %>
                        <td colspan='5'>No Record Found</td>
                        <% end %>
                </tr>
                <% @subjects.each do |subject| %>
                    <tr>
                        <th scope="row">
                            <%= subject.position %>
                        </th>
                        <td>
                            <%= subject.name %>
                        </td>
                        <td>
                            <%= subject.visible %>
                        </td>
                        <td>
                            <%= subject.pages.size %>
                        </td>
                        <td>
                            <%= link_to('View Page', {:controller=> 'pages', :subject_id => subject.id}, class:'btn
                                btn-success') %>
                                <%= link_to('Show', {:action=> 'show', :id => subject.id}, class:'btn btn-warning') %>
                                    <%= link_to('Edit', {:action=> 'edit', :id => subject.id}, class:'btn
                                        btn-secondary') %>
                                        <%= link_to('Delete', {:action=> 'delete', :id => subject.id}, class:'btn
                                            btn-danger') %>
                        </td>
                    </tr>
                    <% end %>
            </tbody>
        </table>

app/views/subjects/new.html.erb
<% @page_title='Subject' %>
    <div class="container">
        <%= link_to('Back', {:action => 'index'}, class:'btn btn-light ') %>

    <div class="ms-5 mt-3 ps-3 bg-light col-5">
    
        <h1>Create Form</h1>
        <%= form_with model: @subject, url:{:action=> 'create', html: { multipart: true }}, method: :post do |f| %>
            <!-- < % = form_for(:admin_user, :url =>{:action => 'create'}) do |f| %> -->

            <%= render(:partial=> 'form', :locals => {:f => f}) %>
                <div class="ms-5">
                    <%= submit_tag('Create', class: 'btn btn-success mb-3' ) %>
                </div>
    </div>
    <% end %>
        </div>

app/views/subjects/show.html.erb
<% @page_title="Subject" %>

    <%= link_to('Back to Subject', {:action=> 'index'}, class:'btn btn-light') %>

        <div class="col-6 bg-light p-2 mt-5">
            <h5>Position</h5>
            <p>
                <%= @subject.position || 'no position yet' %>
            </p>
            <h5>Subject Name</h5>
            <p>
                <%= @subject.name %>
            </p>
            <h5>Visible</h5>
            <p>
                <%= @subject.visible %>
            </p>
            <h5>Image</h5>
            <p>
                <% if @subject.image.content_type.in?(%w[image/jpeg, image/png]) %>
                <%= image_tag @subject.image_as_thumbnails if @subject.image.attached? %>
                <% end %>
            </p>
            <h5>Created At</h5>
            <p>
                <%= @subject.created_at %>
            </p>
            <h5>Updated At</h5>
            <p>
                <%= @subject.updated_at %>
            </p>
        </div>