config/routes.rb
Rails.application.routes.draw do
 
  root 'publics#index'

resource :tests, :except => [:show]

  
  # pubic controller route
  get 'show/:permalink', to: 'publics#show'

  # user controller routes
  get '/login', to: 'users#login'
  post '/login_attempt', to: 'users#login_attempt'
  get 'admin/logout', to: 'users#logout'
  get 'admin/index', to: 'users#index'

  # AdminUser Controller routes
  get 'admin/users/index', to: 'admin_users#index', as: 'index_admin'
  get 'admin/users/new', to: 'admin_users#new', as: 'new_admin'
  post 'admin/users/create', to: 'admin_users#create', as: 'create_admin'
  get 'admin/users/:id/edit', to: 'admin_users#edit', as: 'edit_admin'
  post 'admin/users/:id', to: 'admin_users#update', as: 'update_admin'
  get 'admin/users/:id', to: 'admin_users#destroy', as: 'destroy_admin'

  # Subject Controller routes
  get 'admin/subjects/index/', to: 'subjects#index', as: 'index_subject'
  get 'admin/subjects/show', to: 'subjects#show', as: 'show_subject'
  get 'admin/subjects/new', to: 'subjects#new', as: 'new_subject'
  post 'admin/subjects/create', to: 'subjects#create', as: 'create_subject'
  get 'admin/subjects/:id/edit', to: 'subjects#edit', as: 'edit_subject'
  post 'admin/subjects/users/:id', to: 'subjects#update', as: 'update_subject'
  get 'admin/subjects/:id/delete', to: 'subjects#delete'
  post 'admin/subjects/:id', to: 'subjects#destroy'

  # Pages Controller route
  get 'admin/subjects/pages/index', to: 'pages#index'
  get 'admin/subjects/pages/new', to: 'pages#new'
  get 'admin/subjects/pages/:id', to: 'pages#show'
  post 'admin/subjects/pages/create', to: 'pages#create'
  get 'admin/subjects/pages/:id/edit', to: 'pages#edit'
  post 'admin/subjects/pages/:id', to: 'pages#update'
  get 'admin/subjects/pages/:id/delete', to: 'pages#delete'
  delete 'admin/subjects/pages/:id', to: 'pages#destroy'


  # Section Controller route
  get 'admin/subjects/pages/sections/index', to: 'sections#index'
  get 'admin/subjects/pages/sections/new', to: 'sections#new'
  get 'admin/subjects/pages/sections/:id', to: 'sections#show'
  post 'admin/subjects/pages/sections/create', to: 'sections#create'
  get 'admin/subjects/pages/sections/:id/edit', to: 'sections#edit'
  post 'admin/subjects/pages/sections/:id', to: 'sections#update'
  get 'admin/subjects/pages/sections/:id/delete', to: 'sections#delete'
  delete 'admin/subjects/pages/sections/:id', to: 'sections#destroy'

  match ':controller(/:action(/:id))', :via => [:get, :post]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

    has_secure_password
    has_and_belongs_to_many  :pages
    has_many :section_edits
    has_many :sections, :through => :section_edits, :foreign_key => 'section_id'

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    
    
    validates :first_name,  :presence => true,
                            :length => { :maximum => 20}
                            # :null => false
    validates :last_name,   :presence => true,
                            :length => { :maximum => 20}
                            # :null => false
    validates :username,    :presence => true,
                            :length => {:within => 5..30}
                            # :null => false
    validates  :email,  :presence => true,
                        :length => { :maximum => 40},
                        :format => VALID_EMAIL_REGEX,
                        :confirmation => true

    

    


    scope :sorted, lambda{order('last_name ASC','first_name ASC')}

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  before_action :confirm_logged_in

  def index
    @users = AdminUser.sorted
  end

  def new
    @user = AdminUser.new
  end

  def create
    @user = AdminUser.new(user_params)
    if @user.save
      flash[:success] = 'User Added Successfully'
      redirect_to(:action => 'index')
    else
      render('new')
    end

  end

  def edit
    @user = AdminUser.find(params[:id])
  end

  def update
    @user = AdminUser.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'User data Updated successfully'
      redirect_to(:action => 'index')
    else
      render('edit')
    end
  end

  def destroy
    @user = AdminUser.find(params[:id]).destroy
    flash[:success] = 'User deleted Successfully'
    redirect_to(:action => 'index')
  end

  private
  def user_params
    params.require(:admin_user).permit(:first_name, :last_name, :username, :email, :password)
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<div class="form">
    <div class="input-form">
        <%= f.label(:first_name) %>
            <p>
                <%= f.text_field(:first_name, class:'form-control') %>
                    <% if @user.errors.any? %>
                        <span class='error'>
                            <ul>
                                <% @user.errors.full_messages_for(:first_name).each do |message| %>
                                    <li class="text-danger">
                                        <%= message %>
                                    </li>
                                    <% end %>
                            </ul>
                        </span>
                        <% end %>
            </p>
    </div>
    <div class="input-form">
        <%= f.label(:last_name) %>
            <p>
                <%= f.text_field(:last_name, class:'form-control') %>
                    <% if @user.errors.any? %>
                        <span class='error'>
                            <ul>
                                <% @user.errors.full_messages_for(:last_name).each do |message| %>
                                    <li class="text-danger">
                                        <%= message %>
                                    </li>
                                    <% end %>
                            </ul>
                        </span>
                        <% end %>
            </p>
    </div>
    <div>
        <%= f.label(:username) %>
            <p>
                <%= f.text_field(:username, class:'form-control') %>

                    <% if @user.errors.any? %>
                        <span class='error'>
                            <ul>
                                <% @user.errors.full_messages_for(:username).each do |message| %>
                                    <li class="text-danger">
                                        <%= message %>
                                    </li>
                                    <% end %>
                            </ul>
                        </span>
                        <% end %>
            </p>
    </div>
    <div>
        <%= f.label(:email) %>
            <p>
                <%= f.text_field(:email, class:'form-control') %>
                    <% if @user.errors.any? %>
                        <span class='error'>
                            <ul>
                                <% @user.errors.full_messages_for(:email).each do |message| %>
                                    <li class="text-danger">
                                        <%= message %>
                                    </li>
                                    <% end %>
                            </ul>
                        </span>
                        <% end %>
            </p>
    </div>
    <div>
        <%= f.label(:password) %>
            <p>
                <%= f.password_field(:password, class:'form-control') %>
                    <% if @user.errors.any? %>
                        <span class='error'>
                            <ul>
                                <% @user.errors.full_messages_for(:eamil).each do |message| %>
                                    <li class="text-danger">
                                        <%= message %>
                                    </li>
                                    <% end %>
                            </ul>
                        </span>
                        <% end %>
            </p>
    </div>
    <!-- <div>
        < % = f.label(:created_at) %>
            <p>
                < % = f.datetime_select(:created_at, :order => [:month, :day, :year], class:'form-select') %>
            </p>
    </div> -->
</div>

app/views/admin_users/edit.html.erb
<% @page_title='Users' %>

    <%= link_to('Back to Users Table', {:action=> 'index'}, class:'btn btn-light') %>
        <div class="ms-5 mt-3 ps-3 bg-light col-5">

            <h1>Edit Form</h1>
            <!-- < % = form_with(model: @page) do |f| %> -->
            <%= form_with model: @user, url:{:action=>'update', :id => @user.id}, method: :post do |f| %>

                <%= render(:partial=> 'form', :locals => {:f => f}) %>
                    <div class="ms-5">
                        <%= submit_tag("Update", class: 'btn btn-success mb-3' ) %>
                    </div>
        </div>
        <% end %>

app/views/admin_users/index.html.erb
<% @page_title='Users' %>
    <%= link_to('Add New User', new_admin_path, class:'btn btn-light ') %>
<div class="float-end">
<%= link_to(' Admin Menu', {controller: 'users' , action: 'index' }, class:'btn btn-secondary') %>
        <!-- < % = link_to('Sections List', index_section_path, class:'btn btn-warning') %> -->

        </div>

        <table class="table">
            <div class="container">
                <h5 class="mt-2">
                    <%= pluralize(@users.size, 'Total Users' ) %>

                </h5>
                <h1 class="d-flex justify-content-center">Users Table</h1>
            </div>
            <thead>
                <tr>
                    <th scope="col">Last Name</th>
                    <th scope="col">First Name</th>
                    <th scope="col">User Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <th scope="row">
                            <%= user.last_name %>
                        </th>
                        <td>
                            <%= user.first_name %>
                        </td>
                        <td>
                            <%= user.username %>
                        </td>
                        <td>
                            <%= mail_to(user.email) %>
                        </td>
                        <td>
                            <%= link_to 'Edit' , edit_admin_path(user), class:'btn btn-info' %>
                            <%= link_to 'Delete' , destroy_admin_path(user), class:'btn btn-danger' %>
                        </td>
                    </tr>
                    <% end %>
            </tbody>
        </table>

app/views/admin_users/new.html.erb
<% @page_title='Users' %>
    <div class="container">
        <%= link_to('Back', index_admin_path, class:'btn btn-light ') %>

    <div class="ms-5 mt-3 ps-3 bg-light col-5">
    
        <h1>Create Form</h1>
        <%= form_with model: @user, url:{:action=> 'create'}, method: :post do |f| %>
            <!-- < % = form_for(:admin_user, :url =>{:action => 'create'}) do |f| %> -->
    
            <%= render(:partial=> 'form', :locals => {:f => f}) %>
                <div class="ms-5">
                    <%= submit_tag("Sign up", class: 'btn btn-success mb-3' ) %>
                </div>
    </div>
    <% end %>
    </div>